package com.ford.ngsdnvehicle.commands;

public enum StatusCodes {
    COMMAND_PROCESSING, ERROR_DEEP_SLEEP_V2, TCU_FIRMWARE_UPGRADE_IN_PROGRESS_V2, ERROR_COMMAND_SENT_FAILED_RESPONSE, TCU_FIRMWARE_UPGRADE_IN_PROGRESS, SUCCESS
}
